/*
-- Query: 
-- Date: 2016-11-15 15:48
*/
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Radtour',3920,'Winkelmatenweg 8','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.radtourzermatt.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Wellness',3920,'Kirchstrasse 17','indoor',3,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.wellnesszermatt.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Erlebniswanderung',3920,'Steinmattstrasse 320','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.erlebniswanderung.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Schlittschuh',3920,'Riedstrasse 84','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.schlittschuh.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Museum',3920,'Metzggasse 10','indoor',2,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.museumzermatt.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Minigolf',3920,'Am Bach 3','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.minigolfzermatt.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Schneeschuhwanderung',3920,'Triftweg 282','outdoor',3,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 946 29 39','www.schneeschuh.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Curling',3930,'Wieristrasse 84','indoor',2,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 342 23 23','www.curlingvisp.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Velodrome',3930,'Talstrasse 9','outdoor',2,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 342 23 23','www.velodrome.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Fitness im Freien',3930,'Napoleonstrasse 9a','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 342 23 23','www.fitnessimfreien.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Weindegustation',3930,'Treichweg 3','indoor',3,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 342 23 23','www.weindegustation.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Audio-Guide durch Alt Visp',3930,'La Poste-Platz 4','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 342 23 23','www.audio-guide.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Hallenbad',1950,'Rue St.Guerin 31','indoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 432 12 12','www.hallenbadsitten.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Suone & Spaziergänge',1950,'Avenue de la Gare 22','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 432 12 12','www.suone-sitten.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Eisbahn von Tourbillon',1950,'Rue des Mareches 8','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 432 12 12','www.eisbahnvontourbillon.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Weindegustation',1950,'Route de Vissigen 150','indoor',2,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 432 12 12','www.weindegu.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Kino',1950,'Rue Ste Marguerite 21','indoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 432 12 12','www.kinosion.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Wanderung',3900,'Bahnhofstrasse 14','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 722 12 29','www.wanderung-simplon.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Thermalquellen Brigerbad',3900,'Thermalbad 1','outdoor',3,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 722 12 29','www.thermal-brigerbad.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Apropos Paintball',3900,'Kantinsstrasse 408','indoor',2,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 722 12 29','www.apropospaintball.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Crazy Wheels',3900,'Kantonweg 320','indoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 722 12 29','www.crazywheels.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Fondation Barry du Gyard Saint Bernard',1920,'Route des Chantons 52','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 469 11 11','www.fondation-bgsb.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Palp Festival',1920,'Rue du College 20','indoor',3,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 469 11 11','www.palpfestival.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Tea Time',1920,'Rue de L\'Eglise 7','indoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 469 11 11','www.teatime.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Eisbahn',1920,'Place du Pre-de Foire ','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 469 11 11','www.eisbahn-martigny.ch');
INSERT INTO `aktivitaet` (`aktivitaet_id`,`name`,`ort_id`,`adresse`,`indoor_outdoor`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Piscine municipale',1920,'Rue de Forum 19','outdoor',1,NULL,'At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ','Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.','027 469 11 11','www.piscine-municipale.ch');
