/*
-- Query: 
-- Date: 2016-11-15 11:06
*/
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'St. Lucia',3920,'Bahnhofstrasse 11',1,2,NULL,'Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'La Cucina',3920,'Poststrasse 9',1,3,NULL,'Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Mamma Mia',3920,'Hofweg 31',1,1,NULL,'Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Huan Li',3920,'Bahnhofstrasse 5',2,1,NULL,'Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Goldene Ente',3920,'Hallerstrasse 3',2,2,NULL,'Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Lilly\'s',3920,'Honigweg 6',2,2,NULL,'Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Sterne',3920,'Müllerstrasse 12',3,2,NULL,'Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Fondue Egga',3920,'Wallisserstrasse 24',3,1,NULL,'Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ',NULL,NULL);
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Krone',3920,'Steinweg 2',3,3,NULL,'Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ',NULL,NULL);
