/*
-- Query: 
-- Date: 2016-11-15 15:43
*/
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'St. Lucia',3920,'Bahnhofstrasse 11',1,2,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 967 66 78','www.stlucia.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'La Cucina',3920,'Poststrasse 9',1,3,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 967 28 28','www.lacucina.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Mamma Mia',3920,'Hofweg 31',1,1,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 967 39 99','www.mammamia.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Huan Li',3920,'Bahnhofstrasse 5',2,1,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 967 88 88','www.huanli.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Goldene Ente',3920,'Hallerstrasse 3',2,2,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 967 12 22','www.goldeneente.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Lilly\'s',3920,'Honigweg 6',2,2,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 967 44 55','www.lillys.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Sterne',3920,'Müllerstrasse 12',3,2,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 967 66 67','www.sterne.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Fondue Egga',3920,'Wallisserstrasse 24',3,1,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 967 77 87','www.fondueegge.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Krone',3920,'Steinweg 2',3,3,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 967 23 33','www.krone.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'La Toscana',3930,'Krummweg 3',1,2,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 948 88 49','www.latoscana.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Molto Bene',3930,'Bundesstrasse 2',1,1,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 946 60 60','www.moltobene.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Vincenzo',3930,'Oberstrasse 9',1,3,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 948 40 44','www.ristorantevincenzo.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Tiger',3930,'Talweg 5',2,1,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 946 12 12','www.tiger-visp.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Kirschblüte',3930,'Kirschweg 22',2,2,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 948 22 20','www.kirschblüte.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Restaurant Saigon',3930,'Marktplatz 1',2,3,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 946 65 65','www.saigon.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Bären',3930,'Bärenplatz 3',3,1,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 948 88 80','www.restibären.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Schlosshof',3930,'Hofweg 2',3,3,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 946 12 12','www.schlosshof.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Il Faro',1950,'Vispstrasse 10',1,2,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 322 21 21','www.ilfaro.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Ristorante Luce',1950,'Bahnhofstrasse 3',1,3,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 322 12 19','www.ristoranteluce.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Li Chan',1950,'Bahnhofstrasse 5',2,1,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 322 99 20','www.lichan.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'India',1950,'Kreuzweg 3',2,2,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 322 12 12','www.restaurantindia.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Schützenhof',1950,'Schützenstrasse 4',3,2,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 322 22 23','www.schützenhof-stitten.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Restaurant Meier',1950,'Kronenstrasse 2',3,3,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 322 10 10','www.restaurantmeier.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Il Grissino',3900,'Kreuzstrasse 4',1,2,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 924 44 10','www.ilgrissino.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Dolce Vita',3900,'Hallerstrasse 13',1,1,'NULL','Unser Restaurant bietet ca. 120 – 130 Gästen eine gemütliche Atmosphäre im Raum Terra oder im speziellen Raum Mare, wo ein grosses Meerwasser-Aquarium im Mittelpunkt steht, welches Klein und Gross begeistert. Geniessen Sie bei schönem Wetter auf der gedeckten Terrasse des Restaurants die Sonne wie in Italien.','Erleben Sie bei uns echte italienische Gastfreundschaft.','027 924 10 12','www.dolcevita.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Restaurant Mr. Rung',3900,'Bahnhofplatz 12',2,2,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 924 23 24','www.mrrung.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Hou Hou',3900,'Kellerweg 23',2,1,'NULL','Gönnen Sie sich von unser Team aus dem fernen Osten, ausgewählte Köstlichen. Erleben Sie in unser chinesisches Restaurant, das kulinarische Reich.','Sie werden viel über unsere chinesische- und asiatische Küche erfahren, überzeugen Sie sich selbst!','027 924 44 10','www.houhou.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Schwanen',3900,'Papierweg 21',3,2,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 924 21 29','www.schwanen-brig.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Restaurant Matterhorn',3900,'Mattenweg 8',3,1,'NULL','Was wir unseren Gästen auftischen, ist nicht weit hergeholt, sondern frisch aus der Region. Im Sommer tafeln Sie auf unserer einladenden Terrasse und schauen dem Treiben der einheimischen Bevölkerung zu.','Wir verwöhnen Sie mit exzellenter Schweizer Küche. ','027 924 10 12','www.restimatterhorn.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Il Baccio',1920,'Rue de la Gare 5',1,2,'NULL','Vous pourrez déguster nos plats goûteux sur une grande terrasse ombragée. Nos cuisiniers fidèles vous préparent une cuisine italienne et traditionnelle afin de satisfaire notre clientèle qui se déplace de tout le Valais.','Nous vous accueillons dans un cadre familial, dans une ambiance typique avec un coin café et une salle de restaurant de 75 couverts au caractère boisé.','027 722 23 12','www.ilbaccio.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Croce Bianca',1920,'Rue de l\'Eglise 20',1,3,'NULL','Vous pourrez déguster nos plats goûteux sur une grande terrasse ombragée. Nos cuisiniers fidèles vous préparent une cuisine italienne et traditionnelle afin de satisfaire notre clientèle qui se déplace de tout le Valais.','Nous vous accueillons dans un cadre familial, dans une ambiance typique avec un coin café et une salle de restaurant de 75 couverts au caractère boisé.','027 722 20 20','www.crocebianca.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Kung Fu',1920,'Avenue du Grand 45',2,2,'NULL','Notre restaurant subsiste pour perpétuer la tradition d’une cuisine chinoise qui navigue entre tradition et adaptation aux goûts de par chez nous.','Bienvenue dans votre restaurant chinois, un lieu mythique accessible à tous !','027 722 90 00','www.kungfu.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Jia Wei',1920,'Rue de Lausanne 3',2,1,'NULL','Notre restaurant subsiste pour perpétuer la tradition d’une cuisine chinoise qui navigue entre tradition et adaptation aux goûts de par chez nous.','Bienvenue dans votre restaurant chinois, un lieu mythique accessible à tous !','027 722 23 12','www.jiawei.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Chez Pierre',1920,'Rue de Sion 23',3,3,'NULL','Notre restaurant est une adresse incontournable pour les amateurs de bonne cuisine française et de valeurs sûres.','Lieu idéal pour l’organisation des cocktails dinatoires, soirées privées ou anniversaires, n\'hésitez pas à nous contacter pour de plus amples renseignements.','027 722 12 12','www.chezpierre.ch');
INSERT INTO `restaurant` (`restaurant_id`,`name`,`ort_id`,`adresse`,`kueche_id`,`preis`,`foto`,`beschreibungstext`,`lead`,`telefon`,`website`) VALUES (NULL,'Le Poisson',1920,'Avenue de la Gare 22',3,2,'NULL','Notre restaurant est une adresse incontournable pour les amateurs de bonne cuisine française et de valeurs sûres.','Lieu idéal pour l’organisation des cocktails dinatoires, soirées privées ou anniversaires, n\'hésitez pas à nous contacter pour de plus amples renseignements.','027 722 32 32','www.lepoisson.ch');
