-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 10:43:48 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 155425_3_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `155425_3_1` ;

-- -----------------------------------------------------
-- Schema 155425_3_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `155425_3_1` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `155425_3_1` ;

-- -----------------------------------------------------
-- Table `155425_3_1`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`restaurant` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`restaurant` (
  `restaurant_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `ort_id` INT NULL,
  `adresse` VARCHAR(45) NULL,
  `kueche_id` INT NULL,
  `preis` INT NULL,
  `foto` VARCHAR(45) NULL,
  `beschreibungstext` VARCHAR(250) NULL,
  `lead` VARCHAR(250) NULL,
  `telefon` INT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `155425_3_1`.`aktivität`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`aktivität` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`aktivität` (
  `aktivitaet_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `ort_id` INT NULL,
  `adresse` VARCHAR(45) NULL,
  `indoor_outdoor` VARCHAR(45) NULL,
  `preis` INT NULL,
  `foto` VARCHAR(45) NULL,
  `beschreibungstext` VARCHAR(250) NULL,
  `lead` VARCHAR(250) NULL,
  `telefon` INT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`aktivitaet_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `155425_3_1`.`bewertung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`bewertung` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`bewertung` (
  `bewertung_id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(250) NULL,
  `sterne` INT NULL,
  `kategorie_id` INT NULL,
  `bewertungcol` VARCHAR(45) NULL,
  `angebot_id` INT NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`bewertung_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `155425_3_1`.`kategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`kategorie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`kategorie` (
  `kategorie_id` INT NOT NULL AUTO_INCREMENT,
  `auswahl` VARCHAR(45) NULL,
  PRIMARY KEY (`kategorie_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `155425_3_1`.`kueche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`kueche` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`kueche` (
  `kueche_id` INT NOT NULL AUTO_INCREMENT,
  `art` VARCHAR(45) NULL,
  PRIMARY KEY (`kueche_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `155425_3_1`.`ort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `155425_3_1`.`ort` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `155425_3_1`.`ort` (
  `ort_id` INT NOT NULL,
  `ortsname` VARCHAR(45) NULL,
  PRIMARY KEY (`ort_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
